### ISSUE TITLE
Problème playerDropped

### ISSUE THREAD

**Issue by Fita93** [FXServer-ESX/fxserver-esx_service#1]
Lorsqu'on se déconnecte la source est égale à "Disconnected"
AddEventHandler('playerDropped', function(source)
	print(source) <-- Disconnected
	for k,v in pairs(InService) do
		if v[source] == true then
			v[source] = nil
		end
	end
	print("playerDropped")
	print(to_string(InService))<-- {"true"}
end)

Problème les personnes sont toujours considérées "En service"

**Comment by indilo53** [comment]
Essaie la dernière version je viens de faire un commit

**Comment by Fita93** [comment]
Désolé du retard. Oui ça fonctionne nickel. Merci
